server {
    listen 8088;
    server_name localhost;

    client_max_body_size 80m;

    root /data/projects/Rogein/site/web/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:18790;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header X-Map-File-Name $http_x_map_file_name;
        proxy_set_header X-Map-Width $http_x_map_width;
        proxy_set_header X-Map-Height $http_x_map_height;
    }

    location /media/ {
        alias /data/projects/Rogein/site/media/;
        expires 7d;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
